[serverConfig]
appName = "gochat"
host = "0.0.0.0"
port = 8000
tlsEnabled = false
sslRedirect = false
tlsCertFile = ""
tlsKeyFile = ""

[mysqlConfig]
host = "127.0.0.1"
port = 3306
user = "root"
password = "123456"
databaseName = "gochat"
network = "tcp"
socketPath = "/var/run/mysqld/mysqld.sock"

[redisConfig]
host = "127.0.0.1"
port = 6379
password = ""
db = 0

[authCodeConfig]
accessKeyID = ""
accessKeySecret = ""
signName = ""
templateCode = ""
schemeName = ""
countryCode = "86"
codeLength = 6
validTime = 300
duplicatePolicy = 1
interval = 60
codeType = 1
caseAuthPolicy = 1
returnVerifyCode = false
autoRetry = 1

[logConfig]
logPath = "./logs/gochat.log"

[kafkaConfig]
messageMode = "channel" # channel or kafka
hostPort = "127.0.0.1:9092"
loginTopic = "login"
chatTopic = "chat_message"
logoutTopic = "logout"
partition = 0
timeout = 1

[staticSrcConfig]
staticAvatarPath = "./static/avatars"
staticFilePath = "./static/files"
